### PR TITLE
Updated joint_account model

### PR DESCRIPTION
**Pull request by k5tuck**
Made suggested changes to Joint Accounts model - based on a "Junction Table"

### CODE REVIEW

**Review by shoel-uddin — APPROVED** [review]
Thats a lot of members

**Comment by k5tuck** [comment]
> Thats a lot of members

They should have all been taken off and replaced by one member_id. 
Where they not?

**Review by shoel-uddin — APPROVED** [review]
looks good

**Review by Stormy110 — COMMENTED** [review]
Would the member_id be an integer data type instead of string?

**Review by Stormy110 — APPROVED** [review]

**Pull request merged**
